import Foundation

/// Smart selective compaction system
/// Unlike CLI's nuclear compaction, this preserves critical context
@MainActor
final class CompactionEngine: ObservableObject {
    @Published var isCompacting = false
    @Published var preCompactSnapshot: ContextSnapshot?

    private let contextManager: ContextStateManager

    init(contextManager: ContextStateManager) {
        self.contextManager = contextManager
    }

    // MARK: - Pre-Compaction

    /// Automatically called before any compaction happens
    /// Saves everything that matters so it can be recovered
    func prepareForCompaction(sessionId: String, projectDir: String?) {
        // Respect context pin — skip compaction when pinned
        guard !contextManager.isContextPinned else { return }

        // Take a full snapshot
        preCompactSnapshot = contextManager.takeSnapshot(sessionId: sessionId)

        // Write CONTEXT_STATE.md to project directory
        if let dir = projectDir {
            contextManager.writeContextState(to: dir)
        }

        // Save snapshot to disk for recovery
        saveSnapshot(preCompactSnapshot!)
    }

    /// Generate a reinjection prompt that preserves critical context
    /// This gets prepended to the conversation after compaction
    func generateReinjectionPrompt() -> String? {
        guard let snapshot = preCompactSnapshot else { return nil }

        var prompt = "## Critical Context (preserved through compaction)\n\n"

        if let task = snapshot.currentTask {
            prompt += "**Active task:** \(task)\n\n"
        }

        if !snapshot.decisions.isEmpty {
            prompt += "**Key decisions:**\n"
            for d in snapshot.decisions.suffix(5) {
                prompt += "- \(d.description)\n"
            }
            prompt += "\n"
        }

        if !snapshot.fileChanges.isEmpty {
            prompt += "**Recent file changes:**\n"
            for f in snapshot.fileChanges.suffix(10) {
                prompt += "- `\(f.filePath)`: \(f.summary)\n"
            }
            prompt += "\n"
        }

        if !snapshot.activeConstraints.isEmpty {
            prompt += "**Active constraints:**\n"
            for c in snapshot.activeConstraints {
                prompt += "- \(c)\n"
            }
            prompt += "\n"
        }

        if !snapshot.nextSteps.isEmpty {
            prompt += "**Next steps:**\n"
            for step in snapshot.nextSteps {
                prompt += "- \(step)\n"
            }
        }

        return prompt
    }

    // MARK: - Hook Integration

    /// Generate a PreCompact hook script that auto-saves context
    func generatePreCompactHook(projectDir: String) -> String {
        return """
        #!/bin/bash
        # Auto-generated by Conductor
        # Saves context state before compaction

        CONTEXT_FILE="\(projectDir)/CONTEXT_STATE.md"
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        echo "# Context State (Pre-Compaction)" > "$CONTEXT_FILE"
        echo "*Saved: $TIMESTAMP*" >> "$CONTEXT_FILE"
        echo "" >> "$CONTEXT_FILE"
        echo "## Warning: Context was compacted" >> "$CONTEXT_FILE"
        echo "Read this file to recover context from the previous conversation state." >> "$CONTEXT_FILE"
        """
    }

    /// Install the PreCompact hook into Claude CLI settings
    func installPreCompactHook(projectDir: String) {
        let home = FileManager.default.homeDirectoryForCurrentUser.path
        let settingsPath = "\(home)/.claude/settings.json"

        // Read existing settings
        var settings: [String: Any] = [:]
        if let data = FileManager.default.contents(atPath: settingsPath),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            settings = json
        }

        // Add PreCompact hook
        var hooks = settings["hooks"] as? [String: Any] ?? [:]
        hooks["PreCompact"] = [
            ["type": "command", "command": "cat \(projectDir)/CONTEXT_STATE.md 2>/dev/null || true"]
        ]
        settings["hooks"] = hooks

        // Write back
        if let data = try? JSONSerialization.data(withJSONObject: settings, options: .prettyPrinted) {
            try? data.write(to: URL(fileURLWithPath: settingsPath))
        }
    }

    // MARK: - Persistence

    private func saveSnapshot(_ snapshot: ContextSnapshot) {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let snapshotsDir = appSupport.appendingPathComponent("Conductor/snapshots", isDirectory: true)
        try? FileManager.default.createDirectory(at: snapshotsDir, withIntermediateDirectories: true)

        let file = snapshotsDir.appendingPathComponent("\(snapshot.id).json")
        if let data = try? JSONEncoder().encode(snapshot) {
            try? data.write(to: file)
        }
    }
}
